import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      // The clean-boot e2e server's Next build dir (PM #103). Same generated
      // output as `.next/**` above, different name because two `next dev`
      // processes cannot share one build dir — and a name the `.next/**` glob
      // does not match, which floods the gate with 176 generated-code errors.
      ".next-clean-boot/**",
      "node_modules/**",
      "data/**",
      // Local-only data backups (gitignored). Contain copies of user PROJECT
      // source trees that are not Orchestra code — linting/typechecking them
      // floods the gate with errors from foreign projects. Mirrors the
      // tsconfig.json `exclude` entry.
      "data-backups/**",
      // Agent tooling (gitignored). `.claude/worktrees/<name>/` holds a FULL
      // second copy of the repository, so the root-anchored ignores below
      // (`src/lib/vendor/**`, `refactor-wizards.js`) do NOT match their nested
      // twins — a single worktree floods the gate with 100+ errors. CI never
      // sees this (the directory is gitignored), so it breaks only the local
      // gate, and through `prebuild` the local build. (The original offender
      // was a vendored pdf.js bundle, deleted 2026-08-25; a worktree checked
      // out at an older commit still carries it.)
      ".claude/**",
      "playwright-report/**",
      "test-results/**",
      // Generated by `npm run test:coverage` (lcov-report ships vendored JS).
      // Without this, a local lint run AFTER a coverage run picks up the
      // generated files and reports spurious warnings. See QA audit F-17.
      "coverage/**",
      "bundled-skills/**",
      // ANY custom Next build dir, not just the clean-boot one. Same gap the
      // `.gitignore` had: enumerating one name means the next value of
      // `ORCHESTRA_NEXT_DIST_DIR` floods the gate instead. Measured — running a
      // second server with `.next-login` put 91 generated files into `npm run
      // lint`, turning 22 warnings into 213 errors.
      ".next-*/**",
      // Gitignored local working directory (`/scratch/` in .gitignore).
      "scratch/**",
      // Vendored third-party code — not ours to lint. Currently matches
      // nothing (the last occupant, a pdf-parse copy, was deleted 2026-08-25);
      // kept so the next vendored drop is ignored by default rather than
      // discovered as 100+ lint errors.
      "src/lib/vendor/**",
      // Next.js auto-generated.
      "next-env.d.ts",
      // Ad-hoc one-off scripts at repo root.
      "refactor-wizards.js",
      "test-key-validation.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // Project-wide rule tuning. Rationale:
    //   - no-explicit-any: vendor SDK surfaces (AI SDK, Vercel, Next handlers)
    //     leak `any` through chains we don't control. Treating each instance
    //     as a CI-blocking error punishes intent without changing reality.
    //     Warning keeps it visible without turning CI red on legacy debt.
    //   - prefer-const / ban-ts-comment / no-unescaped-entities: same logic —
    //     keep visible, do not block CI. Tighten incrementally as the codebase
    //     gets cleaned up.
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "prefer-const": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "react/no-unescaped-entities": "warn",
    },
  },
  {
    // Test files routinely have unused destructuring (mock signatures) and
    // `any` for stub data. Loosen there so the rules are signal in app code.
    files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];

export default eslintConfig;
